name: cc_fraud
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.3
  - geopy=2.4.1
  - geopandas=0.14.2
  - haversine=2.9.0
  - kagglehub=0.3.5
  - numpy=2.2.0
  - pandas=2.2.3
  - rapidfuzz=3.10.1
  - scikit-learn=1.5.1
  - swifter=1.4.0
  - xgboost=2.1.3
  - notebook=7.2.2
  - pip=24.3.1
  - pip:
      - wandb==0.18.7
      - geodatasets==2024.8.0