wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.3
    cli_version: 0.18.7
    framework: xgboost
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1733942579
    t:
      1:
      - 5
      - 6
      - 53
      - 55
      2:
      - 5
      - 6
      - 53
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.12.3
      5: 0.18.7
      8:
      - 2
      - 3
      - 5
      13: windows-amd64
booster:
  desc: null
  value: gbtree
device:
  desc: null
  value: cuda
eval_metric:
  desc: null
  value: auc
learning_rate:
  desc: null
  value: 0.1
max_depth:
  desc: null
  value: 3
random_state:
  desc: null
  value: 10
tree_method:
  desc: null
  value: hist
