_wandb:
    value:
        cli_version: 0.18.7
        code_path: code/model/train_test_split.py
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 5
                - 53
                - 55
            "2":
                - 5
                - 53
                - 55
            "3":
                - 2
                - 23
                - 55
            "4": 3.12.3
            "5": 0.18.7
            "8":
                - 2
                - 3
                - 5
            "12": 0.18.7
            "13": windows-amd64
